### ISSUE TITLE
QueryTree Not able to fetch New tables created in MYSQL container 

### ISSUE THREAD

**Issue by dshah2012** [d4software/QueryTree#109]
Hello ,

Steps to reproduce the issue
1 I am using the latest docker image of query tree and also mysql.
2. Created a docker-compose.yml to spin up the containers and communicate.
3. Logged in query tree webpage
4.  Created a db connection with mysql container.
5. Got a Connection Successful Message.
6. Clicked on create report for that conection.
7. Displays tables that are existed.
8. Created new tables in mysql container.
9. Refresh the querytree webpage, New tables created are not displayed.

PS: When I delete the connection in querytree and again add it then it shows. Also second way when I restart my containers it shows.

Is it normal that it will behave this way. It should have taken the tables on the go as it has already created connection with the mysql container in the beginning.
 
Here is my docker-compose file.
```
version: '3.2'
services: 
    reports:
        image: d4software/querytree:latest
        networks: 
            - frontend
            - backend
        container_name: nextreport
        ports: 
            - 8090:80
    mysql:
        image: mysql:latest
        restart: always
        volumes: 
            - ${DATABASE_STORAGE}:/var/lib/mysql
        networks: 
            - backend
        ports: 
            - 3309:3006
        environment: 
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${CUSTOM_USER}
            MYSQL_PASSWORD: ${CUSTOM_PASSWORD}
        container_name: mysql    
networks: 
    frontend:
    backend:
```
